### ISSUE TITLE
Make the buttons center aligned and enhance the css

### ISSUE THREAD

**Issue by Pritam0077** [Pritam0077/Meme-Generator-App#14]
Try to make the buttons in the center and add enhance the styling of the buttons

**Comment by xosteve26** [comment]
> Try to make the buttons in the center and add enhance the styling of the buttons

Hey, I've just forked this repository and made certain changes to center the buttons. Below is a preview of it. If you it's alright with you I'd love to make a PR or if any changes need to be made let me know 🙂🙂
![Screenshot 2022-06-29 185356](https://user-images.githubusercontent.com/73709251/176447199-77649799-6bda-4cb2-acf9-dd7bb0a40539.png)

**Comment by Pritam0077** [comment]
Alignment is ok just try to decrease the height of the buttons and make the corners more rounded
Then make a PR

**Comment by xosteve26** [comment]
> Alignment is ok just try to decrease the height of the buttons and make the corners more rounded Then make a PR

I've made the necessary changes and have opened up a PR https://github.com/Pritam0077/Meme-Generator-App/pull/16
