### ISSUE TITLE
Improve Input and Button UI

### ISSUE THREAD

**Issue by AHTHneeuhl** [Pritam0077/Meme-Generator-App#27]
Can I Improve Input and Button UI?

Also can you make add label for hacktoberfest?

**Comment by Pritam0077** [comment]
Try suggesting something else

**Comment by AHTHneeuhl** [comment]
I want to add TypeScript
I want to add CSS-in-JS

**Comment by Pritam0077** [comment]
go for it @AHTHneeuhl
