### ISSUE TITLE
Choose position of text on image, while generating MEMES

### ISSUE THREAD

**Issue by Anuj-Kumar-AJ** [Pritam0077/Meme-Generator-App#29]
Hi @Pritam0077, I have a suggestion for the memes generation app.  It would be wonderful if we can choose the position of the text in the image during meme generation, for example in the Donal triumph image he is showing the book, so we can choose the position of the image so that the text we write can be written in the book he shows.

It would be fun to have this feature in this app.

If you think this will be a good feature assign it to me, and I will be happy to work on that. ):

**Comment by Pritam0077** [comment]
ok go ahead

**Comment by Anuj-Kumar-AJ** [comment]
Hi @Pritam0077, I am sorry but I don't think I can continue to solve this issue, it would be great to let others solve it. So i have removed my assignment.
