### ISSUE TITLE
Upgrading 

### ISSUE THREAD

**Issue by yung-coder** [Pritam0077/Meme-Generator-App#5]
Hey what if we add some more features like dark mode toggle and some more 
customisation in general ..?

**Comment by Pritam0077** [comment]
Nice, go for it Saksham

**Comment by yung-coder** [comment]
Nice, i will start working on it asap..!

**Comment by yung-coder** [comment]
@Pritam0077 
Can I use bootstrap for some styling..?

**Comment by Pritam0077** [comment]
Ok
